apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: kaidi-lin-pipeline-from-scratch-pipeline
  app.kubernetes.io/instance: kaidi-lin-pipeline-from-scratch-pipeline
  app.kubernetes.io/name: kaidi-lin-pipeline-from-scratch-pipeline