apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: example-node-application
  app.kubernetes.io/instance: example-node-application
  app.kubernetes.io/name: example-node-application